## @author Jose Alvarez-Ruiz <jose.alvarez-ruiz@fu-berlin.de>
## @date April 2016

# Prepare kernel to handle gracefully the data sent by the cameras

net.core.rmem_max=12582912
net.core.rmem_default=12582912
net.ipv4.tcp_rmem=12582912 
net.ipv4.tcp_no_metrics_save=1
